### ISSUE TITLE
Clarifications on permissions

### ISSUE THREAD

**Issue by anapaulagomes** [AppCivico/spottingbot#1]
Hey, nice work with _Pegabot_! :)

I'm just curious: why do you need so many permissions to analyze the followers? I don't see how permissions to _post tweets_ or _direct messages_ would help here. Would you mind to tell me? Thanks and keep up the good work!

**Comment by vguillot** [comment]
Hello @anapaulagomes 

Thank you for your feedback!
Indeed these permissions are not required for Pegabot, the authentification is now updated.
